[package]
name = "rustbasic-activitylog"
version = "0.0.8"
edition = "2024"
build = "build.rs"
description = "Activity logging package for the RustBasic Framework."
license = "MIT"
repository = "https://github.com/herisvan321/rustbasic-activitylog"
readme = "README.md"
keywords = ["web", "framework", "activitylog", "logging"]
categories = ["web-programming"]

[lib]
name = "rustbasic_activitylog"
path = "src/lib.rs"

[dependencies]
rustbasic-core = "0.1"

[build-dependencies]

[[bin]]
name = "rustbasic-activitylog"
path = "src/bin/activitylog.rs"
