[package]
name = "rustbasic-activitylog"
version = "0.0.5"
edition = "2024"
build = "build.rs"
description = "Activity logging package for the RustBasic Framework."
license = "MIT"
repository = "https://github.com/herisvan321/rustbasic-activitylog"
readme = "README.md"
keywords = ["web", "framework", "activitylog", "logging"]
categories = ["web-programming"]

[lib]
name = "rustbasic_activitylog"
path = "src/lib.rs"

[dependencies]
rustbasic-core = "0.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.52.1", features = ["full"] }
colored = "3.0.0"
chrono = "0.4.39"

[build-dependencies]
chrono = "0.4.39"

[[bin]]
name = "rustbasic-activitylog"
path = "src/bin/activitylog.rs"
